version: '3.8'

services:
  nginx-waf-ai:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config
      - ./models:/app/models
      - ./logs:/app/logs
      - ./data:/app/data
      - ~/.ssh:/root/.ssh:ro  # SSH keys for nginx node access
    environment:
      - WAF_AI_HOST=0.0.0.0
      - WAF_AI_PORT=8000
      - WAF_AI_LOG_LEVEL=INFO
      - WAF_AI_MODEL_PATH=/app/models/waf_model.joblib
    restart: unless-stopped
    
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    
  nginx-example:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./examples/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./examples/waf_rules:/etc/nginx/conf.d
    restart: unless-stopped
    depends_on:
      - nginx-waf-ai

networks:
  default:
    name: nginx-waf-ai-network
