#!/bin/bash
# Test Summary Script for nginx WAF AI

echo "🛡️  nginx WAF AI - Quick Test Summary"
echo "===================================="
echo ""

echo "📋 Available Testing Methods:"
echo ""
echo "1. Unit Tests:"
echo "   pytest tests/ -v"
echo ""
echo "2. API Test Suite:"
echo "   python test_api.py"
echo ""
echo "3. Full System Demo:"
echo "   python demo.py"
echo ""
echo "4. Interactive API Documentation:"
echo "   Open http://localhost:8000/docs in browser"
echo ""
echo "5. Individual Endpoint Tests:"
echo "   curl http://localhost:8000/health"
echo "   curl http://localhost:8000/api/stats"
echo "   curl http://localhost:8000/api/nodes"
echo "   curl http://localhost:8000/api/rules"
echo ""
echo "6. CLI Interface:"
echo "   python cli.py status"
echo "   python cli.py train --help"
echo ""
echo "📖 Detailed Testing Guide: See TESTING.md"
echo ""
echo "🔧 Current System Status:"
curl -s http://localhost:8000/api/stats | python -m json.tool | grep -E '"ml_engine_trained"|"traffic_collection_active"|"real_time_processing"|"nginx_nodes_count"' | sed 's/^/   /'

echo ""
echo "✅ System Ready for Testing!"
